import { ActionIcon, Button, Grid, Image, useMantineColorScheme } from '@mantine/core';
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link';
import styled from 'styled-components'
import { MdNightlightRound } from 'react-icons/md'
import { HiLightBulb } from 'react-icons/hi'
import Cards from '../components/Card';

const Container = styled.div`
  
`;

const Home: NextPage = () => {
  const { colorScheme, toggleColorScheme } = useMantineColorScheme();
  const dark = colorScheme === 'dark';

  return (
    <div>
      <Head>
        <title>Youtube Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Container>
        <ActionIcon
          variant="outline"
          color={dark ? 'yellow' : 'blue'}
          onClick={() => toggleColorScheme()}
          title="Toggle color scheme"
        >
          {dark ? <MdNightlightRound size={18} /> : <HiLightBulb size={18} />}
        </ActionIcon>
      </Container>

      <div>
        <Grid>
          <Grid.Col span={4}>
            <Cards />
          </Grid.Col>
          <Grid.Col span={4}>
            <Cards />
          </Grid.Col>
          <Grid.Col span={4}>
            <Cards />
          </Grid.Col>
        </Grid>
      </div>

    </div>
  )
}

export default Home
