import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

const Container = styled.div`
  display: flex;
  background-color: #000;
  color: #fff;
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Youtube Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Container>
        Hello
      </Container>

    </div>
  )
}

export default Home
